### ISSUE TITLE
Deciding on a target system

### ISSUE THREAD

**Issue by hkedjnane** [LifeInvaders/game#18]
J'ai réalisé le script Unity/PUN2 pour l'assignation des cibles au cours d'une partie.
Cependant je l'ai réalisé selon certaines règles qui me semblent adéquates basés sur les critères suivants:

-réalisabilité : le système est cohérent d'un point de vu fonctionnel et logique, il fonctionne sur papier et est implémentable
(note: pas FACILEMENT, juste implémentable, je m'occupe d'écrire le code et je pense pouvoir dire si c'est possible ou pas)

-simplicité: le système est très facile à comprendre. L'objectif n'est pas non plus de rendre ce système impénétrable pour l'utilisateur! On doit pouvoir expliquer de façon CLAIRE et CONCIS comment fonctionne le système/le script.

-jouabilité: le PLUS important, c'est que le système soit logique d'un point de vue gameplay. Il faut qu'il supporte un gameplay fun et intéressant pour le joueur. Cet aspect est prioritaire sur la simplicité(mais évidemment pas sur la réalisabilité)

Pour l'instant, voici les conditions qui ont été posés:

-un joueur ne peut pas être sa propre cible(duh)

-deux joueurs ne peuvent pas s'entretuer
J'ai choisi cela car on n'a pas encore de mécaniques d'attaque.  Si on dit que deux joueurs se chassent l'un l'autre, il faut un système qui soit cohérent d'un point de vue 1v1. Ca rajoute une part de complexité sur le système de combat (qui est très superflu pour un jeu d'arcade, surtout pour une mécanique qui à mon avis n'apporte rien de particulier)
De plus si deux joueurs se dirigent l'un vers l'autre ils sont sûr de se rencontrer, et on réduit considérablement les possibiltés.
Imaginez une partie à 4 joueurs. Les chances de composer 2 couples de 2 sont assez importantes. Au final on a juste des 1v1 sur la map, alors que si on respecte l'idée du "chasseur et chassé" on a beaucoup plus d'interactions entre les joueurs. Encore une fois ce n'est pas un jeu de combat, mais un jeu d'arcade/de déduction... se battre en face à face n'a pas beaucoup de sens.

-pour l'instant, UN chasseur et UN chassé.
Je peux imaginer un système ou plusieurs joueurs en chasse un. Cependant, ce choix ne doit pas être fait au hasard, ou systématiquement. Il faut une mécanique qui détermine le nombre de chasseurs chassant une personne. Cette mécanique ne me parait pas nécessaire au possible, mais s'il n'y en a pas, ce serait une très mauvaise idée de laisser le tirage faire ce choix sans raison particulière. C'est unfair, et surtout, pour un nombre faible de joueurs, les chances d'avoir un 3v1 à 4 par exemple sont beaucoup trop élevés. Deuxième problème, 
Donc encore une fois, proposez un système permettant d'assigner plusieurs chasseurs à la même cible (si possible un pas trop complexe pour l'instant) mais sinon, par défaut, UN chasseur UN chassé.

Pas grand chose, juste 3 conditions(dont une plutôt obvious) qui déterminent le choix des cibles.

Si vous avez des idées de modifications/d'ajout etc... Proposez-les en réponse.

Ensuite, le deuxième problème: REASSIGNER LES CIBLES.

Pour l'instant, mon idée: un simple timer. Un temps imparti pendant lequel les joueurs doivent tuer leur cible. A la fin du timer, cible tué ou pas, on assigne une nouvelle cible.

POINTS FORTS:
-système le plus simple qu'on puisse imaginer! 
-crée une tension: tuer sa cible le plus vite possible.
Pour détailler: le timer pousse le joueur à tuer sa cible. Celui-ci peut même pousser à l'erreur. Voir sa cible alors qu'il reste 10 secondes au timer, ça peut être vraiment un moment de gameplay génial.
On peut également donner plus de points aux personnes tuant leur cible en premier/le plus vite.
Cela crée également un système de "rounds" qui donne une progression à la game, progression avec laquelle on peut interagir avec d'autres systèmes (chaque round peut-être différent)
J'avais également pensé à avoir un timer de quelques minutes qui peut se réduire au fil des kills. En gros, quand un joueur tue un autre, on peut retirer du temps. Encore une fois le but et d'augmenter la tension.
POINT FAIBLE:
-En vrai y en a surtout un: le joueur qui tue sa cible doit attendre un certain temps avant d'en avoir une nouvelle.
CONTRE-ARGUMENT:
On peut toujours trouver des trucs à faire. Aussi il faut qu'il échappe à sa cible. Mais en soit on peut définitivement trouver de quoi occuper le joueur le temps qu'il retrouve une cible.
-De même pour les joueurs décédés, ils doivent attendre un peu avant de respawn
CONTRE-ARGUMENT:
le joueur va probablement devoir attendre de toutes façons. Il faut tout de même une pénalité pour être mort! Mais j'avais l'idée d'un mode spectateur à la Among Us où le joueur peut se balader sur la map sous la forme d'un squelette invisible. il faudrait désactiver les collisions avec les joueurs vivants/les NPCs cependant, mais je pense que l'on peut utiliser les layers pour cela. Effectivement on peut filtrer les collisions en fonction du système de Layers sur Unity.

Principalement: c'est simple et clair. Concrètement le système est parfait et sans faille. On peut peut-être imaginer un peu plus dynamique et fun. Mais il faut quand même une certaine cohérence, on peut pas juste balancer des cibles au hasard au joueur. Un système alternatif est difficile à imaginer principalement dû au fait de la règle un chasseur un chassé. Encore une fois cette règle n'est pas essentiel, mais on peut vraiment pas juste dire arbitrairement "bah toi maintenant t'es ciblé par 7 personnes have fun". C'est complètement stupide et très frustrant/anti-jeu au possible. Il faut une logique derrière cette décision.

Bon voilà, encore une fois faites vos propositions :)

**Comment by Renaud-Dov** [comment]
Pour le fait d'avoir plusieurs chasseurs à ses trousses, il peut être proportionnel au nb de joueurs dans la partie.

Le système de timer est une bonne idée. En revanche, je ne suis pas fan d'une deadcam... Il faudrait plutôt une killcam ou juste un écran de menu pour choisir sa classe

**Comment by lafreuxpabo** [comment]
"Donc encore une fois, proposez un système permettant d'assigner plusieurs chasseurs à la même cible (si possible un pas trop complexe pour l'instant)"
On s'en occupe mardi prochain, un tableau et un marqueur et je t'explique mon idée


"-En vrai y en a surtout un: le joueur qui tue sa cible doit attendre un certain temps avant d'en avoir une nouvelle."
On peut faire des trucs bonus, comme un cible supplémentaire.(du coup on a deux joueurs sur 1 mais ca met la pression au joueur visé donc au final c'est pas plus mal)
