### ISSUE TITLE
[Other] -  Unlimited FPS

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#19]
Le jeu génère un nombre faramineux d'images par seconde.

Le problème, comme l'a signalé notre ACDC, ça bouffe énormément les capacités du GPU du joueur. Sachant que la plupart des animations sont aux alentours de 30 fps, il faudrait donc bloquer le nombre de fps que l'on propose, à 30 par exemple.

On pourrait aussi donner la possibilité au joueur de le changer dans les paramètres.

**Comment by hkedjnane** [comment]
Je pense qu'on peut se contenter d'une option vsync en vrai étant donné que Unity propose cette option.
Par contre le cap max ne doit pas être aussi bas, Unlimited c'est pas bon bien sûr mais un bon cap c'est 200-300fps (et du coup avec vsync à 60)
Les animations avaient l'air tout à fait naturel même à 300+fps donc pas besoin de se limiter aux fps des anims.

A noter que perso je tourne déjà à 30 fps sur ma surface  en Ultra et que c'est vraiment pas agréable ^^
