### ISSUE TITLE
[Other] - Update Animations Frame

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#20]
Est ce que, par rapport  à **l'issue #19**, on devrait implémenter des animations qui ont plus de 30 frames ? et les adapter suivant que le joueur active un mode 60fps ou + ou non.

 ### Note : Le problème, c'est qu'on pourrait avoir un nombre de frame par animation différent d'une anim à l'autre.

**Comment by hkedjnane** [comment]
Hmm, mais pourtant sur l'éditeur on a déjà joué les animations à 300+fps et elles avaient l'air tout à fait naturel. Si ça posait problème on l'aurait déjà remarqué je pense. Après le pb effectivement c'est d'avoir certaines animations qui paraissent plus fluides que d'autres. Cependant je pense que Unity fait bien le boulot sur ce point, je suspecte que toutes les animations joue au final le même nombres de frames in-game peu importe le nombre de frames in-editor. Au pire on peut cap les animations qui ne le sont pas déjà à 30fps.

Donc perso, je dirais: tant qu'on ne rencontre pas le problème, Wait & See.

**Comment by Renaud-Dov** [comment]
OK
