### ISSUE TITLE
[Feature] - Remove character randomization

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#36]
Il y a actuellement trop de choix quand il génère aléatoirement les personnages. En plus d'avoir sa photo et du radar, il serait impossible de se tromper de cible.

**Comment by lafreuxpabo** [comment]
On va bien etre obligé de toute façon car si le fait de se tromper de cible est impossible, le jeu n'a plus aucun interet.
Mais, on peut toujours réduire le champ des possibilités afin de conserver la variété que nous propose l'asset.
On pourrait faire en sorte que a chaque début de partie, le jeu choisisse un assortiment de 20 skins par exemple. Le jeu ne va utiliser que ces 20 skins pour generer les persos de l'IA, et ne proposera aux joueurs que ces 20 skins

**Comment by hkedjnane** [comment]
Après ça dépend très largement de combien de NPCs on met sur la map... Mais si on fait un rapide calcul, avec un nombre énorme de 100 NPCs sur la map et 20 skins différents, en moyenne chaque skin sera présent 5 fois... La question c'est: est-ce que c'est suffisant? D'un côté ça ne paraît pas beaucoup, mais d'un autre côté ça peut être suffisant. L'alternatif, bien sûr, c'est de trouver un moyen pour aiguiller le joueur autre que de lui donner l'apparence de sa cible par défaut. Dans ce cas là, on peut mettre une infinité de variété! Mais je suis d'accord qu'il faut y réfléchir.

**Comment by Renaud-Dov** [comment]
dans une petite zone, il y a peu de chance malgré tout que tu ais deux NPC qui se ressemblent. Et au pire, on peut choisir la mixité en début de partie
