### ISSUE TITLE
[Gamecore] (Power Boost) - Disguise

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#48]
### Que fait ce pouvoir ?

Ce pouvoir permet de changer d'apparence. Il prend alors l'apparence d'un NPC proche de lui. Si aucun NPC ne se trouve à proximité, alors il prendra une apparence au hasard.

*Si l'idée est accepté, elle ira dans la liste de l'issue #46*

**Comment by Renaud-Dov** [comment]
#### Avant utilisation du pouvoir
![image](https://user-images.githubusercontent.com/14821642/109854131-f981d800-7c56-11eb-9f4a-d94423a09d9a.png)

#### Après utilisation du pouvoir
![image](https://user-images.githubusercontent.com/14821642/109854178-069ec700-7c57-11eb-98a4-bcd932aa47dd.png)

Est-ce que l'on devrait rendre ce pouvoir de déguisement temporaire ou pas ?

**Comment by hkedjnane** [comment]
Etant donné qu'il y a pas encore d'implémentation du système de chasseur, ça dépendra de ça. J'ai mon idée d'implémentation et donc je pense qu'il ne sera pas nécessaire de rendre le pouvoir temporaire mais ça reste à voir! Pour l'instant je dirais, ça ne sert pas de le rendre temporaire.
