### ISSUE TITLE
[Gamecore] (Power Boost) - Speed

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#50]
### Que fait ce pouvoir ?
Ce pouvoir, permet de se déplacer ultra rapidement.

Ce serait juste un pouvoir qui joue une animation de course différente, et qui booste la vitesse pendant plusieurs secondes.
*Si l'idée est accepté, elle ira dans la liste de l'issue #46*

**Comment by Renaud-Dov** [comment]
Que pensez vous de l'idée ?

**Comment by hkedjnane** [comment]
Oui j'avais pensé à un truc pareil. Ca me parait être une bonne idée. Je vois pas trop quel type d'animation différente il pourrait y avoir, mais on pourrait aussi ajouter de la fumée ou un truc comme ca. Ah, et je veux bien m'en occuper aussi. D'ailleurs, un peu hors sujet dans cette issue, mais il faudrait probablement créer un template (je pense à une classe mère abstraite) pour les pouvoirs, surtout si plusieurs personnes font des pouvoirs. Du coup je valide perso :)

**Comment by Renaud-Dov** [comment]
>  il faudrait probablement créer un template (je pense à une classe mère abstraite) pour les pouvoirs

Faudrait surtout regarder mon code déjà disponible ;)

**Comment by Renaud-Dov** [comment]
Et je te laisse t'en occuper 😀

**Comment by hkedjnane** [comment]
Ah! Parfait tout ca.

Et ca part en prod
