### ISSUE TITLE
[Gamecore] (Power Boost) - Throwing Knives

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#54]
### Que fait ce pouvoir ?
Ce pouvoir permet, après avoir verrouillé une cible, de le faire saigner et l'obliger à ralentir et ne pas utiliser ses pouvoirs.
*Si l'idée est accepté, elle ira dans la liste de l'issue #46*

**Comment by hkedjnane** [comment]
Deal!
