### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by Renaud-Dov** [LifeInvaders/game#88]
J'ai essayé de voir le bout de code que propose [TUTOUNITYFR](https://github.com/TUTOUNITYFR/Rich-Presence-Discord-Unity3D). et franchement, on pourrait faire un truc cool !
![image](https://user-images.githubusercontent.com/14821642/120387936-c53bb780-c32a-11eb-9bba-3c17ef3e0b17.png)

On pourrait indiquer s'il est dans un lobby, combien de personnes il attend, etc...

Vous en pensez quoi  @LifeInvaders/dev  ?

**Comment by Renaud-Dov** [comment]
on pourrait faire ça par exemple :
![image](https://user-images.githubusercontent.com/14821642/120389760-22386d00-c32d-11eb-9f84-6e3f67b87d4a.png)
![image](https://user-images.githubusercontent.com/14821642/120389817-38dec400-c32d-11eb-956b-5e0a41aea8af.png)
![image](https://user-images.githubusercontent.com/14821642/120389832-3d0ae180-c32d-11eb-8f51-a00906180866.png)

**Comment by ModEnter** [comment]
ça claque ça

**Comment by Renaud-Dov** [comment]
closed #105
